package com.javabykiran.hibernate;
// Generated 27 Apr, 2020 2:20:51 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Registration generated by hbm2java
 */
@Entity
@Table(name = "registration", catalog = "loginspringmvcjbk")
public class Registration implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idregistration;
	private String name;
	private String phone;
	private String email;
	private String password;

	public Registration() {
	}

	public Registration(String name, String phone, String email, String password) {
		this.name = name;
		this.phone = phone;
		this.email = email;
		this.password = password;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idregistration", unique = true, nullable = false)
	public Integer getIdregistration() {
		return this.idregistration;
	}

	public void setIdregistration(Integer idregistration) {
		this.idregistration = idregistration;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "phone", nullable = false, length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Override
	public String toString() {
		return "Registration [idregistration=" + idregistration + ", name=" + name + ", phone=" + phone + ", email="
				+ email + ", password=" + password + "]";
	}

}
